/*
 * This file is generated by jOOQ.
 */
package com.task.accbook.db;


import com.task.accbook.db.tables.Databasechangeloglock;
import com.task.accbook.db.tables.Salaries;
import com.task.accbook.db.tables.Users;
import com.task.accbook.db.tables.records.DatabasechangeloglockRecord;
import com.task.accbook.db.tables.records.SalariesRecord;
import com.task.accbook.db.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<SalariesRecord, Integer> IDENTITY_SALARIES = Identities0.IDENTITY_SALARIES;
    public static final Identity<UsersRecord, Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = UniqueKeys0.DATABASECHANGELOGLOCK_PKEY;
    public static final UniqueKey<SalariesRecord> SALARIES_PK = UniqueKeys0.SALARIES_PK;
    public static final UniqueKey<SalariesRecord> SALARIES_USER_ID_KEY = UniqueKeys0.SALARIES_USER_ID_KEY;
    public static final UniqueKey<UsersRecord> USERS_PK = UniqueKeys0.USERS_PK;
    public static final UniqueKey<UsersRecord> USERS_NAME_KEY = UniqueKeys0.USERS_NAME_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SalariesRecord, UsersRecord> SALARIES__SALARIES_FK0 = ForeignKeys0.SALARIES__SALARIES_FK0;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<SalariesRecord, Integer> IDENTITY_SALARIES = Internal.createIdentity(Salaries.SALARIES, Salaries.SALARIES.ID);
        public static Identity<UsersRecord, Integer> IDENTITY_USERS = Internal.createIdentity(Users.USERS, Users.USERS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, "databasechangeloglock_pkey", Databasechangeloglock.DATABASECHANGELOGLOCK.ID);
        public static final UniqueKey<SalariesRecord> SALARIES_PK = Internal.createUniqueKey(Salaries.SALARIES, "salaries_pk", Salaries.SALARIES.ID);
        public static final UniqueKey<SalariesRecord> SALARIES_USER_ID_KEY = Internal.createUniqueKey(Salaries.SALARIES, "salaries_user_id_key", Salaries.SALARIES.USER_ID);
        public static final UniqueKey<UsersRecord> USERS_PK = Internal.createUniqueKey(Users.USERS, "users_pk", Users.USERS.ID);
        public static final UniqueKey<UsersRecord> USERS_NAME_KEY = Internal.createUniqueKey(Users.USERS, "users_name_key", Users.USERS.NAME);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<SalariesRecord, UsersRecord> SALARIES__SALARIES_FK0 = Internal.createForeignKey(com.task.accbook.db.Keys.USERS_PK, Salaries.SALARIES, "salaries__salaries_fk0", Salaries.SALARIES.USER_ID);
    }
}
