/*
 * This file is generated by jOOQ.
 */
package com.task.accbook.db;


import com.task.accbook.db.tables.Databasechangelog;
import com.task.accbook.db.tables.Databasechangeloglock;
import com.task.accbook.db.tables.Salaries;
import com.task.accbook.db.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = com.task.accbook.db.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = com.task.accbook.db.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.salaries</code>.
     */
    public static final Salaries SALARIES = com.task.accbook.db.tables.Salaries.SALARIES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = com.task.accbook.db.tables.Users.USERS;
}
